{
 "title": "CNC数据采集程序监控",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "收到数据",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "benthos_input_received" }
   ]
  },
  {
   "title": "输出数据",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "benthos_output_sent" }
   ]
  },
  {
   "title": "接收数据速率",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(benthos_input_received[1m])"
    }
   ]
  },
  {
   "title": "发送数据速率",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "targets": [
    { "expr": "rate(benthos_output_count[1m])" }
   ]
  },
  {
   "title": "输入连接失败/5分钟",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(benthos_input_connection_failed[5m])"
    }
   ]
  }
 ]
}