oracle:
    server: 192.0.0.1
    port: 1521
    servicename: testname
    user: user
    password: pass
kafka:
    server: 127.0.0.1:9092
    topic: cncmqtt3
    consumergroup: mqttinfo
    consumerid: mqttinfo01