oracle:
    server: 192.0.0.01
    port: 1521
    servicename: testname
    user: user
    password: pass
kafka:
    server: 192.168.1.2:9092,192.168.1.3:9092,192.168.1.4:9092
    topic: cncmqtt3
    consumergroup: mqttinfo
    consumerid: mqttinfo01