oracle:
    server: 127.0.0.1
    port: 1521
    servicename: name
    user: user
    password: pass
kafka:
    server: 
        - 127.0.0.1:9092
        - 127.0.0.1:9092
        - 127.0.0.1:9092
    topic: test
    consumergroup: test
    consumerid: test
